# CMake generated Testfile for 
# Source directory: /mnt/data/ntlab/hdy/simpler/tests/ut/cpp
# Build directory: /mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_tensormap "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_tensormap")
set_tests_properties(test_tensormap PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;335;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_ring "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_ring")
set_tests_properties(test_ring PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;336;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_scope "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_scope")
set_tests_properties(test_scope PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;337;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_orchestrator "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_orchestrator")
set_tests_properties(test_orchestrator PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;338;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_scheduler "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_scheduler")
set_tests_properties(test_scheduler PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;339;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_remote_wire "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_remote_wire")
set_tests_properties(test_remote_wire PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;340;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_remote_endpoint "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_remote_endpoint")
set_tests_properties(test_remote_endpoint PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;190;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;341;add_hierarchical_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_child_memory "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_child_memory")
set_tests_properties(test_child_memory PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;309;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;346;add_task_interface_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_chip_max_tensor_args "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_chip_max_tensor_args")
set_tests_properties(test_chip_max_tensor_args PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;309;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;347;add_task_interface_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_call_config "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_call_config")
set_tests_properties(test_call_config PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;309;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;348;add_task_interface_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_chip_callable_upload_immutable "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_chip_callable_upload_immutable")
set_tests_properties(test_chip_callable_upload_immutable PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;366;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_elf_build_id "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_elf_build_id")
set_tests_properties(test_elf_build_id PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;372;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_runtime_orch_so "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_runtime_orch_so")
set_tests_properties(test_runtime_orch_so PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;373;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_device_arena "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_device_arena")
set_tests_properties(test_device_arena PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;380;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_buffer_pool_manager "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_buffer_pool_manager")
set_tests_properties(test_buffer_pool_manager PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;381;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_l3_l2_orch_comm "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_l3_l2_orch_comm")
set_tests_properties(test_l3_l2_orch_comm PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;385;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_trb_runtime_temp_buffer "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_trb_runtime_temp_buffer")
set_tests_properties(test_trb_runtime_temp_buffer PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;412;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_l3_l2_message_queue "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_l3_l2_message_queue")
set_tests_properties(test_l3_l2_message_queue PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;429;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_l3_l2_orch_endpoint "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_l3_l2_orch_endpoint")
set_tests_properties(test_l3_l2_orch_endpoint PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;446;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_l3_l2_orch_comm_service "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_l3_l2_orch_comm_service")
set_tests_properties(test_l3_l2_orch_comm_service PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;462;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_l3_l2_orch_comm_sim_runner "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_l3_l2_orch_comm_sim_runner")
set_tests_properties(test_l3_l2_orch_comm_sim_runner PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;499;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_runtime_timeout_config "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_runtime_timeout_config")
set_tests_properties(test_runtime_timeout_config PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;502;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_runtime_timeout_config_a5 "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_runtime_timeout_config_a5")
set_tests_properties(test_runtime_timeout_config_a5 PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;326;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;506;add_common_utils_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_scope_stats_collector "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_scope_stats_collector")
set_tests_properties(test_scope_stats_collector PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;529;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_orch_so_file "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_orch_so_file")
set_tests_properties(test_orch_so_file PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;549;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a2a3_fatal "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a2a3_fatal")
set_tests_properties(test_a2a3_fatal PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;212;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;555;add_a2a3_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_task_allocator "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_task_allocator")
set_tests_properties(test_task_allocator PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;558;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_dep_list_pool "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_dep_list_pool")
set_tests_properties(test_dep_list_pool PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;559;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_scheduler_state "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_scheduler_state")
set_tests_properties(test_scheduler_state PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;560;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_task_state "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_task_state")
set_tests_properties(test_task_state PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;561;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_ready_queue "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_ready_queue")
set_tests_properties(test_ready_queue PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;562;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_shared_memory "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_shared_memory")
set_tests_properties(test_shared_memory PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;563;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a2a3_tensormap "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a2a3_tensormap")
set_tests_properties(test_a2a3_tensormap PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;564;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_fanin_pool "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_fanin_pool")
set_tests_properties(test_fanin_pool PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;565;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a2a3_orchestrator_fanin "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a2a3_orchestrator_fanin")
set_tests_properties(test_a2a3_orchestrator_fanin PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;139;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;566;add_a2a3_orchestrator_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_spsc_queue "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_spsc_queue")
set_tests_properties(test_spsc_queue PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;567;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_wiring "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_wiring")
set_tests_properties(test_wiring PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;568;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_aicore_completion_mailbox "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_aicore_completion_mailbox")
set_tests_properties(test_aicore_completion_mailbox PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;569;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a2a3_scope_stats_collector "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a2a3_scope_stats_collector")
set_tests_properties(test_a2a3_scope_stats_collector PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;118;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;570;add_a2a3_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_fatal "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_fatal")
set_tests_properties(test_a5_fatal PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;234;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;575;add_a5_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_task_allocator "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_task_allocator")
set_tests_properties(test_a5_task_allocator PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;581;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_dep_list_pool "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_dep_list_pool")
set_tests_properties(test_a5_dep_list_pool PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;582;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_scheduler_state "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_scheduler_state")
set_tests_properties(test_a5_scheduler_state PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;583;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_task_state "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_task_state")
set_tests_properties(test_a5_task_state PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;584;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_ready_queue "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_ready_queue")
set_tests_properties(test_a5_ready_queue PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;585;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_shared_memory "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_shared_memory")
set_tests_properties(test_a5_shared_memory PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;586;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_tensormap "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_tensormap")
set_tests_properties(test_a5_tensormap PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;587;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_fanin_pool "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_fanin_pool")
set_tests_properties(test_a5_fanin_pool PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;588;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_orchestrator_fanin "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_orchestrator_fanin")
set_tests_properties(test_a5_orchestrator_fanin PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;294;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;589;add_a5_orchestrator_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_spsc_queue "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_spsc_queue")
set_tests_properties(test_a5_spsc_queue PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;590;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_wiring "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_wiring")
set_tests_properties(test_a5_wiring PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;591;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a5_aicore_completion_mailbox "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a5_aicore_completion_mailbox")
set_tests_properties(test_a5_aicore_completion_mailbox PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;273;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;592;add_a5_runtime_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_host_log_off "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_host_log_off")
set_tests_properties(test_host_log_off PROPERTIES  _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;611;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
add_test(test_a2a3_aicpu_affinity_select "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/build-urma/test_a2a3_aicpu_affinity_select")
set_tests_properties(test_a2a3_aicpu_affinity_select PROPERTIES  LABELS "no_hardware" _BACKTRACE_TRIPLES "/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;635;add_test;/mnt/data/ntlab/hdy/simpler/tests/ut/cpp/CMakeLists.txt;0;")
